<?xml version="1.0" encoding="utf-8"?>




<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" type="text/css" href="/ad/css/landing.css?v=20170608"/>
    <title></title>
</head>

<body>
<div class="landingBottom">
    <span>京ICP备11000964号-6&nbsp;&nbsp;|&nbsp;&nbsp;中国联通版权所有</span>
    <var>
        
            
                
                
                    
                
                
                
                
            
                
                    
                
                
                
                
                
            
                
                
                
                
                    
                
                
            
                
                
                
                
                
                    
                
            
                
                
                
                    
                
                
                
            
                
                
                
                
                
            
            <a href="http://mail.wo.cn/mail/adAccess.action?adSpaceId=web_login_05&amp;adId=5&amp;provinceCode=0&amp;link=5xqUP4YzmF0V%2FQhkGLAInquPGbsovtCfH3ZF%2BQcorQ%2B%2F9QJqVJTZ2BqgL60BtwUB" target="_blank"
               style="color: ;font-size: ">
                法律声明
            </a>
        
            
                
                
                    
                
                
                
                
            
                
                    
                
                
                
                
                
            
                
                
                
                
                    
                
                
            
                
                
                
                
                
                    
                
            
                
                
                
                    
                
                
                
            
                
                
                
                
                
            
            <a href="http://mail.wo.cn/mail/adAccess.action?adSpaceId=web_login_05&amp;adId=4d1159d1&amp;provinceCode=0&amp;link=5xqUP4YzmF0V%2FQhkGLAIngxQq6BC2WKePRoakhW9oOm%2BRr3ZhAAqN%2BVOSTHkL%2Fbx" target="_blank"
               style="color: ;font-size: ">
                联系我们
            </a>
        
            
                
                
                    
                
                
                
                
            
                
                    
                
                
                
                
                
            
                
                
                
                
                    
                
                
            
                
                
                
                
                
                    
                
            
                
                
                
                    
                
                
                
            
                
                
                
                
                
            
            <a href="http://mail.wo.cn/mail/adAccess.action?adSpaceId=web_login_05&amp;adId=2dd1f3a5&amp;provinceCode=0&amp;link=zMn1X62tWcImUHZkRolk04tNH2Hnt5ViB2%2BNrcLKcpM%3D" target="_blank"
               style="color: ;font-size: ">
                客服受理
            </a>
        
            
                
                
                    
                
                
                
                
            
                
                    
                
                
                
                
                
            
                
                
                
                
                    
                
                
            
                
                
                
                
                
                    
                
            
                
                
                
                    
                
                
                
            
                
                
                
                
                
            
            <a href="http://mail.wo.cn/mail/adAccess.action?adSpaceId=web_login_05&amp;adId=c2bb83ae&amp;provinceCode=0&amp;link=5xqUP4YzmF0V%2FQhkGLAInrKJwp3XwGXrXqrgp6GTGPAO5ALIjg8zTGwOLYKyfoZ64FoicVJLJM8q6IjDX%2FVuXA%3D%3D" target="_blank"
               style="color: ;font-size: ">
                炫功能
            </a>
        
    </var>
</div>
</body>
</html>

