﻿﻿﻿﻿define({
	root:{
	
		Logon:
		{
			LOGON_OLBNKING_USERNAME_TITLE : "登录到网上银行：用户名 | 汇丰",
			LOGON_LOGON : "登录",
			LOGON_ENTER_USERNAME : "输入您的用户名",
			LOGON_CONTINUE : "继续",
			LOGON_CANCEL : "取消",
			LOGON_LINKING_TEXT:"为提供更佳保障，在透过环球账户服务连结您的户口之前，我们会验证您在<国家名>网上银行的登录资料。 ",
			LOGON_VERIFYING : "验证中",
			LOGON_FORGOT_USERNAME : "忘记用户名？",
			LOGON_REMEMBER_ME : "记住我",
			LOGON_DONT_TICK_HELP : "如果您使用的是公共场所电脑或共享设备，请勿勾选此框",
			LOGON_NOT_REGISTERED : "未注册",
			LOGON_ERROR_USERNAME : "请输入一个有效的用户名.",
			LOGON_USERNAME_HELP : "用户名帮助",
			LOGON_TEXT_HELP_COPY1 : "这是您在注册网上银行时选择的唯一用户名。",
			LOGON_TEXT_HELP_COPY2 : "用户名必须至少由 6 个字符组成。",
			LOGON_TEXT_HELP_COPY_EXAMPLE1 : "例如 IB1234567890 或 John@123",
			LOGON_FORGOTUSERNAME_LINK: "<a class='normalIcon' href='https://www.eu462.p2g.netd2.hsbc.com.hk/1/2/HSBCINTEGRATION/forgotten' target='_blank'>忘记用户名？ <span class='hidden'>Open in a new window </span></a>", 
			LOGON_NOT_REGISTERED_LINK: "/gsa?idv_cmd=idv.SaaSSecurityCommand&SaaS_FUNCTION_NAME=Saas_Registration&COUNTRY_CODE=CN&GROUP_MEMBER_CODE=HSBC&locale=zh_CN&ProductType=PBK&CustomerType=PFS&APPNAME=HUBPIB&IC_GSM_APPID=GSP_IC_CN",
			DOB_MM: '月月',
			DOB_DD: '日日',
			DOB_YYYY: '年年年年'
		},

		BrowserWarning:{
			BROWSER_NOT_SUPPORTED_WARNING_TEXT:'我们检测到您的浏览器已经过时',
			BROWSER_NOT_SUPPORTED_TEXT:'使用此浏览器可能会导致部分页面显示不正确。<br/>我们建议您使用下列浏览器的<B>最新版本</B>登陆网上银行账户，以获得最佳网上体验：<br/>• 谷歌浏览器<br/>• 火狐浏览器<br/>• IE浏览器(适用于Windows)<br/>• Safari 浏览器(适用于Macintosh OS)<br/><br/>更多信息，请浏览我们的<a href =https://www.hsbc.com.cn/1/2/online-security-cn/security target =_blank>网上保安</a> 页面。'
			},
		
		
		PasswordPage:
		{
			LOGON_OLBNKING_PASSWORD_TITLE : "使用密码登录到网上银行 | 汇丰",
			LOGON_USING_SECURE_CODE_TITLE:"使用安全密码登录到网上银行 | 汇丰",
			LOGON_GREET_USER : "你好",
			LOGON_GREET_USER_GOOD: "",
			LOGON_GREET_USER_MORNING: "早上好",
			LOGON_GREET_USER_AFTERNOON: "下午好",
			LOGON_GREET_USER_EVENING: "晚上好",
			LOGON_NOT : "不是<name of user>  ",			
			LOGON_SWITCH_USERNAME : "?",
			LOGON_ENTER_PASSWORD : "输入您的密码",
			LOGON_FORGOTTEN_PASSWORD : "忘记密码？",
			LOGON_WITH_SECURITY_CODE : "使用安全密码",
			LOGON_SHOW_HIDE_USER_DETAILS:"显示或隐藏用户信息",
			LOGON_SHOW_USER_DETAILS:"显示用户信息",
			LOGON_PASSWORD_HELP : "密码帮助",
			LOGON_PASSWORD_CONDN : "这个是你在网上银行设置的密码.<br/>密码长度介于 8-30 字符之间，且必须包含数字 (0-9) 和字母 (A-Z)。",
			LOGON_PASSWORD_HELP_FORGOTTEN : "如果忘记密码，您可选择“忘记密码？”重置密码。<br/>你再不需要提供您的提示答案。",			
			LOGON_PASSWORD_HELP_TEXT1 : "这个是你在网上银行设置的密码.",
			LOGON_USERNAME_NOMATCH : "您输入的信息与我们的记录不符。 ",
			LOGON_DOB_PSWD_TO_ENTER : "请输入您的出生日期和安全密码以便继续",		//
			LOGON_ENTER_DOB : "输入您的出生日期",
			LOGON_INVALID_DATE : "请输入两位数字作为你的生日日期， 例如：9号输入09。",
			LOGON_INVALID_MONTH : "请输入两位数字作为你的生日月份， 例如：11月输入11。",
			LOGON_INVALID_YEAR : "请输入四位数字作为你的生日年份， 例如：1970年输入1970。",
			LOGON_DOB_HELP : "出生日期帮助",
			LOGON_DOB_HELP_TEXT1:"在汇丰，我们知道网上银行的安全对您很重要。",
			LOGON_DOB_HELP_TEXT2:"为安全起见，我们需要您确认出生日期以验证您的身份。",
			LOGON_DOB_EXAMPLE1:"例如： 12 31 1970",
			LOGON_USERNAME_SECURE_CODE_MISMATCH:"您输入的用户名和安全密码与我们的记录不符。",
			LOGON_DOB_SECURE_CODE_TO_PROCEED:"请输入您的出生日期和安全密码以便继续",
			LOGON_SECURE_KEY_TITLE:"安全密码器",
			LOGON_SECURE_KEY_HELP:"安全密码器方面的帮助",
			LOGON_SECURE_KEY_HELP_TITLE:"安全密码器帮助<br/><span style='font-size: 15px;'>使用安全密码器生成 6 位数的安全密码。</span>",
			LOGON_SECURE_KEY_NEED_HELP:"需要获得安全密码器方面的帮助？",
			LOGON_FORGOT_SECUREKEY_PIN:"忘记安全密码器 密码？ ",
			LOGON_LOST_DAMAGED_SECUREKEY:"安全密码器丢失、损坏或被盗？ ",
			LOGON_INVALID_SECURECODE_DOB:"您输入的用户名或安全密码与我们的记录不符。 请重试 。",
			LOGON_FORGOT_SECUREKEY_PASSWORD:"忘记安全密钥的密码",
			LOGON_LOST_DAMAGED_DEVICE:"安全密钥丢失、损坏或被盗 ",
			LOGON_DOB_SECURE_KEY_HELP:"生日日期和安全密钥帮助信息",
			LOGON_ENTER_SECURE_CODE:"请输入您的安全密码",
			LOGON_HOW_TO_GENERETE_SECURE_CODE:"如何生成安全密码",
			LOGON_GENERETE_SECURE_CODE_STEP1:"Step 1",
			LOGON_GENERETE_SECURE_CODE_TEXT1:"按住绿色按钮开启安全密码器，然后输入您的安全密码器密码",
			LOGON_GENERETE_SECURE_CODE_STEP2:"Step 2",
			LOGON_GENERETE_SECURE_CODE_TEXT2_1:"在显示的汇丰欢迎屏幕上，",
			LOGON_GENERETE_SECURE_CODE_TEXT2_2:" 按下绿色按钮。 ",
			LOGON_GENERETE_SECURE_CODE_TEXT2_3:"此操作将生成一个安全密码。",
			LOGON_GENERETE_SECURE_CODE_STEP3:"Step 3",
			LOGON_GENERETE_SECURE_CODE_TEXT3:"安全密码器屏幕上将显示 6 位数的安全密码。",
			LOGON_GENERETE_SECURE_CODE_MOB_TEXT1_1:"在您的移动设备上启动\“HSBC Mobile Banking\”（汇丰移动银行）应用，然后选择 ",
			LOGON_GENERETE_SECURE_CODE_MOB_TEXT1_2:"生成安全码",
			LOGON_GENERETE_SECURE_CODE_MOB_TEXT2_1:"输入数字安全密码器密码，然后选择",
			LOGON_GENERETE_SECURE_CODE_MOB_TEXT2_2:"生成",
			LOGON_GENERETE_SECURE_CODE_MOB_TEXT3:"此时将显示 6 位数的登录安全码。",
			LOGON_GENERETE_SECURE_CODE_GO_TEXT1:" 按下您的安全设备上的灰色按钮以生成安全码。",
			LOGON_GENERETE_SECURE_CODE_GO_TEXT2:"在下面的字段中输入您的安全设备上显示的安全码。",			
			LOGON_USING_PSWD:"使用密码登录",
			LOGON_PSWD_SUSPENDED:"密码已被暂停使用",
			LOGON_PSWD_SUSPENDED_TEXT1:"由于登录尝试失败的次数过多，为安全起见，我们已暂时中止您使用密码登录到汇丰网上银行。  ",
			LOGON_PSWD_SUSPENDED_TEXT2:"您可在稍后尝试使用密码登录。",			
			LOGON_PSWD_SUSPENDED_CONTINUE:"要继续使用，您可采用以下方式：",
			LOGON_PSWD_SUSPENDED_CONTINUE_STEP1:"&nbsp;使用安全密码立即登录；或者",
			LOGON_PSWD_SUSPENDED_CONTINUE_STEP2:"&nbsp;稍后使用密码重试",
			LOGON_INVALID_DOB_HELP:"<br/>如果您认为我们可能记录错了您的出生日期，请致电客户服务部 。<br/>•卓越理财客户<br/>800-820-8828（限中国内地固话拨打）<br/>(+86)-400-820-8828 / (+86)-(21)-3888 8828（适用于境外或移动电话拨打）<br/>24小时服务(包括节假日)<br/> •运筹理财客户<br/>800-820-8878（限中国内地固话拨打）<br/>(+86) 400-820-8878 / (+86)-(21)-3888 8878（适用于境外或移动电话拨打）<br/>24小时服务(包括节假日)<br/>•其他个人理财客户 <br/>800-830-2880（限中国内地固话拨打）<br/>(+86)-400-820-3090 / (+86)-(21)-3888 3015（适用于境外或移动电话拨打）<br/>周一至周五: 08:30-17:30 (节假日除外) ",
			LOGON_START_PASSWORD_RESET:" 开始恢复密码",
			LOGON_SECURE_KEY_SUSPENDED:"安全密码被暂停使用",
			LOGON_SECURE_KEY_SUSPENDED_TEXT1:"由于登录尝试失败的次数过多，我们已暂时中止您使用安全码访问汇丰网上银行。 ",
			LOGON_SECURE_KEY_SUSPENDED_CONTINUE_STEP1:" 立即使用密码登录；或者",
			LOGON_SECURE_KEY_SUSPENDED_CONTINUE_STEP2:"稍后使用安全码重试",
			LOGON_USE_PSWD:"使用密码",
			LOGON_RETURN_HOMEPAGE:"返回主页 ",
			LOGON_CAM40_SOTP_OVERLAY_TEXT:"卡遗失，被盗 或 安全密码器损坏，请致电客服中心。 <br/>•卓越理财客户<br/>800-820-8828（限中国内地固话拨打）(+86)-400-820-8828 / (+86)-(21)-3888 8828（适用于境外或移动电话拨打）<br/>24小时服务(包括节假日)<br/>•运筹理财客户<br/>800-820-8878（限中国内地固话拨打）(+86) 400-820-8878 / (+86)-(21)-3888 8878（适用于境外或移动电话拨打）<br/>24小时服务(包括节假日)<br/>•其他个人理财客户 <br/>800-830-2880（限中国内地固话拨打）(+86)-400-820-3090 / (+86)-(21)-3888 3015（适用于境外或移动电话拨打）<br/>周一至周五: 08:30-17:30 (节假日除外) ", 
			LOGON_CAM40_OTP_OVERLAY_CONTINUE_VALUE:"继续",
			LOGON_GENERETE_PREV: "上一个",
			LOGON_GENERETE_NEXT: "下一个",
			LOGON_SHOW_PASSWORD:"Show"
		},
		
		LockedPassword:
		{
			LOGON_LOCKED_PASSWORD:"在密码被锁定的情况下登录",
			LOGON_LOCKED_PASSWORD_TEXT1:"密码多次输入错误。 为安全起见，您的密码已被锁定。",
			LOGON_LOCKED_PASSWORD_TEXT2:"现在您必须执行简单的步骤完成密码恢复流程，才能继续使用。",
			LOGON_LOCKED_PASSWORD_CONTINUE:"要继续使用，您可采用以下方式：",
			LOGON_LOCKED_PASSWORD_CONTINUE_STEP1:"使用安全密码立即登录；或者",
			LOGON_LOCKED_PASSWORD_CONTINUE_STEP2:"执行几个简单的步骤重置密码",
			LOGON_USE_SECURE_CODE:" 使用安全密码",
			LOGON_START_PASSWORD_RECOVERY:" 开始重置密码"
		},
		
		LockedSecureKey:
		{			
			LOGON_LOCKED_SECURE_KEY:"安全密码已被锁定",
			LOGON_LOCKED_SECURE_KEY_TEXT1:"安全密码多次输入错误。 为安全起见，我们已锁定您的登录安全密码。",
			LOGON_LOCKED_SECURE_KEY_TEXT2:"请致电客户服务部 。<br/>•卓越理财客户<br/>800-820-8828（限中国内地固话拨打）<br/>(+86)-400-820-8828 / (+86)-(21)-3888 8828（适用于境外或移动电话拨打）<br/>24小时服务(包括节假日)<br/>•运筹理财客户<br/>800-820-8878（限中国内地固话拨打）<br/>(+86) 400-820-8878 / (+86)-(21)-3888 8878（适用于境外或移动电话拨打）<br/>24小时服务(包括节假日)<br/>•其他个人理财客户 <br/>800-830-2880（限中国内地固话拨打）<br/>(+86)-400-820-3090 / (+86)-(21)-3888 3015（适用于境外或移动电话拨打）<br/>周一至周五: 08:30-17:30 (节假日除外) ",
			LOGON_LOCKED_SECURE_KEY_TEXT3:"您也可以选择使用您的密码直接登录。",			
			LOGON_LOCKED_SECURE_KEY_CONTINUE:"要继续使用，您可采用以下方式：",
			LOGON_LOCKED_SECURE_KEY_CONTINUE_STEP1:"使用安全密码立即登录；或者",
			LOGON_LOCKED_SECURE_KEY_CONTINUE_STEP2:" 执行几个简单的步骤重置密码",			
			LOGON_USE_PASSWPRD:" 使用密码",			
			LOGON_RESET_DIGITAL_SECURE_KEY:" 重置安全密码器",
			LOGON_CONTACT_HSBC:" 联系 汇丰",
			LOGON_ERROR:"错误",
			LOGON_SYSTEM_UNAVAILABLE:"系统现在不可用，请稍候再试 .",
			LOGON_SEC_KEY_ACT_PROG:"Secure Key activation in progress",
			LOGON_SEC_KEY_ACT_PROG_TEXT1 :"Activation of your Secure Key is still in process, collect your activation code from the ATM within 24 hours of requesting it.",
			LOGON_SEC_KEY_ACT_PROG_TEXT2 : "When complete you will be able to log on to online banking. ",
			LOGON_BACK : "Back",
			LOGON_PASS_CODE_NULL :"The security code you entered does not match our records. Please try again.",
			LOGON_PROFILE_LOCKED :"账户已锁定",
			LOGON_PROFILE_LOCKED_TEXT1 :"您已经尝试登录太多次失败。为了您的安全，您的个人资料已被锁定。",
			LOGON_PROFILE_LOCKED_TEXT2 :"您必须根据下面简单的步骤来恢复您的账户登录资料。",
			LOGON_START_PASSWORD_RECOVERY:"Start password recovery",
			LOGON_SEC_KEY_ACT_PROG_TEXT3 :"Activation of your Secure Key takes 24 hours and is still in process.<br>When complete you will be able to log on and we will send you SMS confirmation.",
			LOGON_ACC_SUSPDED:"账户已被暂停",
			LOGON_ACC_SUSPDED_TEXT1 :"您的账户似乎存在问题。<br/> 请致电客户服务部门寻求帮助。<br/>•卓越理财客户<br/>800-820-8828（限中国内地固话拨打）<br/>(+86)-400-820-8828 / (+86)-(21)-3888 8828（适用于境外或移动电话拨打）<br/>24小时服务(包括节假日)<br/>•运筹理财客户<br/>800-820-8878（限中国内地固话拨打）<br/>(+86) 400-820-8878 / (+86)-(21)-3888 8878（适用于境外或移动电话拨打）<br/>24小时服务(包括节假日)<br/>•其他个人理财客户 <br/>800-830-2880（限中国内地固话拨打）<br/>(+86)-400-820-3090 / (+86)-(21)-3888 3015（适用于境外或移动电话拨打）<br/>周一至周五: 08:30-17:30 (节假日除外)",
			LOGON_ACPT_TNC :"Please read and accept the Terms & Conditions.",
			LOGON_HT_TEXT1:"我们检测到您的安全密码器电量过低。 您每次打开安全密码器时，它会显示低电量信息 2 秒钟。",
			LOGON_HT_TEXT2:" 之后，您可通过生成安全密码继续登录。 要更换安全密码器，请致电客户服务部。 [LOG_0011]<br/>•卓越理财客户<br/>800-820-8828（限中国内地固话拨打）(+86)-400-820-8828 / (+86)-(21)-3888 8828（适用于境外或移动电话拨打）<br/>24小时服务(包括节假日)<br/>•运筹理财客户<br/>800-820-8878（限中国内地固话拨打）(+86) 400-820-8878 / (+86)-(21)-3888 8878（适用于境外或移动电话拨打）<br/>24小时服务(包括节假日)<br/>•其他个人理财客户 <br/>800-830-2880（限中国内地固话拨打）(+86)-400-820-3090 / (+86)-(21)-3888 3015（适用于境外或移动电话拨打）<br/>周一至周五: 08:30-17:30 (节假日除外)",
			LOGON_DSK_RST:"Reset your Digital Secure Key Password",
			LOGON_DSK_RST_TEXT1:"Open the HSBC mobile banking app and select Generate Security Code",
			LOGON_DSK_RST_TEXT2:"Select the Help button in the top right of the Digital Secure Key page",
			LOGON_DSK_RST_TEXT3:"Select reset Digital Secure Key password from the list",
			LOGON_DSK_RST_TEXT4:"Enter your existing Digital Secure Key password then select Confirm",
			LOGON_DSK_RST_TEXT5:"Enter a new Digital Secure Key password then re-entre it and select Confirm",
			LOGON_CONTACT_HSBC_LINK:"https://www.hsbc.com.cn/1/2/misc-cn/contact-us?WABFormEntryCommand=cmd_prefill"	
			},
			InputErrorMsg:
			{
				LOGON_MISSING_MESSAGE:"请填写这个字段。",
				LOGON_MISSING_USER_MESSAGE:"请输入一个有效的用户名。",
			    LOGON_INVALID_USER_MESSAGE:"用户名必须包含5至76个字母数字字符。",
				LOGON_INVALID_PASSWORD_MESSAGE:"密码必须包含8至30个字母数字字符。",
				LOGON_INVALID_SECURECODE_MESSAGE:"安全密码必须包含6个字母数字字符。",
				LOGON_CONTINUE:"继续",
				LOGON_INVALID_DAY_MESSAGE:"请输入两位数字作为你的生日日期， 例如：9号输入09。",
				LOGON_INVALID_MONTH_MESSAGE: "请输入两位数字作为你的生日月份， 例如：11月输入11。",
				LOGON_INVALID_YEAR_MESSAGE:"请输入四位数字作为你的生日年份， 例如：1970年输入1970。",
				USERID_VALIDATION_PATTERN : "^[A-Za-z0-9-@\\'._-\\s*]{5,76}"
				
			}
	}
	
});